Repository validatedpatterns/docs, pull requests merged in 2023-11, with the labels that each got.

#338 Installing the tooling dependencies is already in Prerequisites.
  modules/mcg-deploying-mcg-pattern.adoc
Labels: lgtm, needs-ok-to-test, size/XS

#355 Clarify automation message
  .github/workflows/preview-message.yml
Labels: size/XS

#337 Make the sentence easier to read.
  content/learn/quickstart.adoc
Labels: lgtm, needs-ok-to-test, size/XS

#356 Fix two mistakes in IE
  content/patterns/industrial-edge/getting-started.md
Labels: size/XS

#357 Rename group everywhere
  archetypes/pattern/_index.adoc
  content/patterns/emerging-disease-detection/_index.adoc
  content/patterns/emerging-disease-detection/getting-started.adoc
  content/patterns/medical-diagnosis/_index.adoc
  content/patterns/multicloud-gitops/_index.adoc
  layouts/partials/footer.html
Labels: size/S

#358 Updated vault info
  content/learn/vault.adoc
Labels: size/S

#359 Drop note about seldon
  content/ci/_index.md
  content/patterns/industrial-edge/_index.md
Labels: size/S

#362 Modularize edd
  content/patterns/emerging-disease-detection/_index.adoc
  content/patterns/emerging-disease-detection/edd-getting-started.adoc
  modules/edd-about-emerging-disease-detection.adoc
  modules/edd-architecture.adoc
  modules/edd-deploying-edd-pattern.adoc
  modules/edd-using-edd-pattern.adoc
  static/images/emerging-disease-detection/edd-kubeframe.png
Labels: size/L

#360 Clarify unseal process
  content/learn/vault.adoc
Labels: size/XS

#365 HyperShift Doc Scaffolding
  content/patterns/hypershift/_index.adoc
  modules/comm-attributes.adoc
  static/images/hypershift/hypershift-high-level-architecture.png
Labels: lgtm, size/M

#367 Added the common attributes file to all assembly/main adoc files
  README.md
  content/contribute/background-on-pattern-development.adoc
  content/contribute/contribute-to-docs.adoc
  content/contribute/creating-a-pattern.adoc
  content/contribute/extending-a-pattern.adoc
  content/contribute/structure.adoc
  content/learn/about.adoc
  content/learn/importing-a-cluster.adoc
  content/learn/infrastructure.adoc
  content/learn/ocp-cluster-general-sizing.adoc
  content/learn/quickstart.adoc
  content/learn/rhel-for-edge-general-sizing.adoc
  content/learn/secrets.adoc
  content/learn/validated.adoc
  content/learn/vault.adoc
  content/learn/workflow.adoc
  content/patterns/emerging-disease-detection/_index.adoc
  content/patterns/emerging-disease-detection/edd-getting-started.adoc
  content/patterns/hypershift/_index.adoc
  content/patterns/multicloud-gitops/_index.adoc
  content/patterns/multicloud-gitops/mcg-cluster-sizing.adoc
  content/patterns/multicloud-gitops/mcg-getting-started.adoc
  content/patterns/multicloud-gitops/mcg-ideas-for-customization.adoc
  content/patterns/multicloud-gitops/mcg-imperative-actions.adoc
  content/patterns/multicloud-gitops/mcg-managed-cluster.adoc
  modules/mcg-about-cluster-sizing.adoc
Labels: size/M

#352 New Validated Patterns tiers
  .gitignore
  content/learn/about-pattern-tiers-types.adoc
  content/learn/community.adoc
  content/learn/implementation.adoc
  content/learn/maintained.adoc
  content/learn/sandbox.adoc
  content/learn/test-artefacts.adoc
  content/learn/tested.adoc
  content/learn/validated.adoc
  modules/comm-attributes.adoc
  modules/comm-vp-manuela-deployment.adoc
  modules/edd-deploying-edd-pattern.adoc
Labels: size/XXL

#368 Fixed link for the maintained pattern
  content/learn/maintained.adoc
Labels: size/XS

#370 updated the demo instructions.
  content/patterns/mlops-fraud-detection/_index.adoc
  content/patterns/mlops-fraud-detection/mfd-getting-started.adoc
  content/patterns/mlops-fraud-detection/mfd-running-the-demo.adoc
  modules/comm-attributes.adoc
  modules/edd-about-emerging-disease-detection.adoc
  modules/edd-deploying-edd-pattern.adoc
  modules/mfd-architecture.adoc
  modules/mfd-deploying-mfd-pattern.adoc
  modules/mfd-using-mfd-demo.adoc
  modules/mfd-using-mfd-pattern.adoc
  static/images/grid.png
  static/images/mlops-fraud-detection/mfd-add-data-connection.png
  static/images/mlops-fraud-detection/mfd-configure-model-server.png
  static/images/mlops-fraud-detection/mfd-data-connection-details.png
  static/images/mlops-fraud-detection/mfd-deployment-model-options.png
  static/images/mlops-fraud-detection/mfd-get-mlflow-port.png
  static/images/mlops-fraud-detection/mfd-mlflow-model-path.png
  static/images/mlops-fraud-detection/mfd-mlflow-view.png
  static/images/mlops-fraud-detection/mfd-open-rhoai.png
  static/images/mlops-fraud-detection/mfd-trained-model.png
  static/images/mlops-fraud-detection/mfd-workbench-settings.png
  static/images/mlops-fraud-detection/mft-create-aiml-project.png
Labels: size/L

#372 fixed some refs and links
  content/patterns/mlops-fraud-detection/_index.adoc
  content/patterns/mlops-fraud-detection/mfd-getting-started.adoc
  modules/mfd-about-mlops-fraud-detection.adoc
  modules/mfd-deploying-mfd-pattern.adoc
Labels: size/XS

#374 updated the hl ref. architecture/markitecture diagram
  modules/edd-architecture.adoc
  static/images/emerging-disease-detection/edd-reference-architecture.png
  static/images/emerging-disease-detection/edd-rh-hl-architecture.png
Labels: size/XS

#366 Blog post for config management plugins 2.0
  content/blog/2023-11-17-argo-configmanagement-plugins.md
Labels: size/L
