Repository validatedpatterns/docs, pull requests merged in 2023-07, with the labels that each got.

#279 Revising CI Status functionality
  config.yaml
  content/blog/_index.md
  content/ci/_index.md
  content/ci/internal.md
  content/contribute/_index.md
  content/learn/_index.md
  content/patterns/_index.md
  content/patterns/ansible-edge-gitops/_index.md
  content/patterns/devsecops/_index.md
  content/patterns/industrial-edge/_index.md
  content/patterns/medical-diagnosis/_index.adoc
  content/patterns/multicloud-gitops-Portworx/_index.md
  content/patterns/multicloud-gitops/_index.adoc
  content/patterns/retail/_index.md
  layouts/_default/index.html
  layouts/ci/single.html
  layouts/list.html
  layouts/partials/ci-key.html
  layouts/partials/ci.html
  layouts/partials/links.html
  layouts/partials/menu-ci.html
  layouts/partials/patterns-index.html
  layouts/partials/site-navigation.html
  layouts/partials/spinner.html
  layouts/patterns/single.html
  layouts/shortcodes/danger.html
  layouts/shortcodes/note.html
  layouts/shortcodes/warning.html
  static/css/custom.css
  static/js/dashboard.v2.js
Labels: lgtm, approved

#281 Minor tweaks to the color and layout of CI Dashboard
  layouts/blog/single.html
  layouts/ci/single.html
  layouts/contribute/single.html
  layouts/learn/single.html
  layouts/partials/ci-key.html
  layouts/partials/patterns-index.html
  layouts/patterns/single.html
  static/css/custom.css
  static/js/dashboard.v2.js
Labels: lgtm

#284 Drop the dates from badges grouped by date
  static/js/dashboard.v2.js
Labels: lgtm

#285 Switching to async loading for badges
  static/js/dashboard.v2.js
Labels: lgtm

#288 Adding a proper 404 page for website
  layouts/404.html
  static/images/404.png
Labels: lgtm, approved

#287 Adding archetype templates to docs site
  archetypes/blog.adoc
  archetypes/contribute.adoc
  archetypes/default.adoc
  archetypes/learn.adoc
  archetypes/pattern/_index.adoc
  archetypes/pattern/additional-pages.adoc.template
  archetypes/pattern/cluster-sizing.adoc
  archetypes/pattern/getting-started.adoc
  archetypes/pattern/ideas-for-customization.adoc
  archetypes/pattern/troubleshooting.adoc
Labels: lgtm, approved

#291 TELCODOCS-1325: Create a snippet for tech preview
  modules/technology-preview.adoc
Labels: lgtm, approved, jira/valid-reference

#292 TELCODOCS-1326: Create a snippet for dev preview
  modules/developer-preview.adoc
Labels: lgtm, jira/valid-reference
