Repository validatedpatterns/docs, pull requests merged in 2023-10, with the labels that each got.

#313 The console.redhat.com site currently has no top-level OpenShift link or menu.
  content/patterns/medical-diagnosis/getting-started.adoc
  content/patterns/multicloud-gitops-Portworx/getting-started.md
  content/patterns/multicloud-gitops-Portworx/managed-cluster.md
  modules/comm-deploying-managed-cluster-using-clusteradm-tool.adoc
  modules/comm-deploying-managed-cluster-using-cm-cli-tool.adoc
  modules/mcg-deploying-managed-cluster-using-rhacm.adoc
  modules/mcg-deploying-mcg-pattern.adoc
Labels: needs-ok-to-test

#312 The original link points to a We Have Moved organization
  layouts/partials/footer.html
Labels: needs-ok-to-test

#323 Updating URLs and links post the migration to the new site and repo
  README.md
  content/blog/2021-12-31-medical-diagnosis.md
  content/blog/2022-03-30-multicloud-gitops.md
  content/blog/2022-09-02-route.md
  content/blog/2022-10-12-acm-provisioning.md
  content/contribute/contribute-to-docs.adoc
  content/contribute/extending-a-pattern.md
  content/learn/faq.adoc
  content/learn/implementation.adoc
  content/learn/secrets.adoc
  content/learn/validated.adoc
  content/learn/workflow.adoc
  content/patterns/ansible-edge-gitops/_index.md
  content/patterns/ansible-edge-gitops/ansible-automation-platform.md
  content/patterns/ansible-edge-gitops/getting-started.md
  content/patterns/ansible-edge-gitops/ideas-for-customization.md
  content/patterns/ansible-edge-gitops/installation-details.md
  content/patterns/ansible-edge-gitops/openshift-virtualization.md
  content/patterns/ansible-edge-gitops/troubleshooting.md
  content/patterns/cockroachdb/_index.md
  content/patterns/connected-vehicle-architecture/_index.md
  content/patterns/devsecops/_index.md
  content/patterns/devsecops/getting-started.md
  content/patterns/devsecops/secure-supply-chain-demo.md
  content/patterns/industrial-edge/_index.md
  content/patterns/industrial-edge/application.md
  content/patterns/industrial-edge/getting-started.md
  content/patterns/industrial-edge/ideas-for-customization.md
  content/patterns/industrial-edge/troubleshooting.md
  content/patterns/kong-gateway/_index.md
  content/patterns/medical-diagnosis/_index.adoc
  content/patterns/medical-diagnosis/ideas-for-customization.adoc
  content/patterns/multicloud-gitops-Portworx/_index.md
  content/patterns/multicloud-gitops-Portworx/ideas-for-customization.md
  content/patterns/multicloud-gitops/_index.adoc
  content/patterns/retail/_index.md
  content/patterns/retail/components.md
  content/patterns/retail/getting-started.md
  content/patterns/retail/troubleshooting.md
  layouts/404.html
  modules/contributing.adoc
  modules/doc-guidelines.adoc
  modules/mcg-deploying-mcg-pattern.adoc
  modules/tools-and-setup.adoc
Labels: lgtm, approved

#327 Updating the Google groups for Validated patterns and other instances…
  modules/tools-and-setup.adoc
Labels: lgtm, approved

#328 converting all .md files to .adoc files under the Contribute content type
  content/blog/2022-12-01-multicluster-devsecops.md
  content/contribute/_index.adoc
  content/contribute/background-on-pattern-development.adoc
  content/contribute/creating-a-pattern.adoc
  content/contribute/extending-a-pattern.adoc
  content/contribute/structure.adoc
  content/contribute/structure.md
Labels: lgtm, approved

#332 Include Nutanix test results in our CI dashboard
  static/js/dashboard.v2.js
Labels: size/XS
