Repository validatedpatterns/docs, pull requests merged in 2023-12, with the labels that each got.

#375 added a link to a demo video and some tidy up
  modules/mfd-about-mlops-fraud-detection.adoc
  modules/mfd-architecture.adoc
Labels: size/S

#330 Changing to the new tiers
  archetypes/pattern/_index.adoc
  content/patterns/ansible-edge-gitops/_index.md
  content/patterns/cockroachdb/_index.md
  content/patterns/connected-vehicle-architecture/_index.md
  content/patterns/devsecops/_index.md
  content/patterns/emerging-disease-detection/_index.adoc
  content/patterns/hypershift/_index.adoc
  content/patterns/industrial-edge/_index.md
  content/patterns/kong-gateway/_index.md
  content/patterns/medical-diagnosis/_index.adoc
  content/patterns/mlops-fraud-detection/_index.adoc
  content/patterns/multicloud-gitops-Portworx/_index.md
  content/patterns/multicloud-gitops/_index.adoc
  content/patterns/retail/_index.md
  layouts/partials/label-maintained.html
  layouts/partials/label-sandbox.html
  layouts/partials/label-tested.html
  layouts/partials/menu-patterns-browser.html
  layouts/partials/patterns-browser.html
  layouts/partials/patterns-index.html
  layouts/patterns/summary-with-image.html
Labels: size/L

#377 Blog: new tier names
  content/blog/2023-12-01-new-pattern-tiers.md
Labels: size/S

#381 Reword two must requirements for the maintained tier
  content/learn/maintained.adoc
Labels: size/XS

#379 Post announcing Nutanix testing
  content/blog/2023-12-05-nutanix-testing.md
Labels: size/S

#383 MCG slide-deck
  modules/mcg-architecture.adoc
Labels: size/XS

#384 mcg demo script
  modules/mcg-architecture.adoc
Labels: lgtm, size/XS

#385 MCG is now maintained
  content/patterns/multicloud-gitops/_index.adoc
Labels: size/XS

#380 Adding "Other products" filter option
  config.yaml
  content/patterns/ansible-edge-gitops/_index.md
  content/patterns/cockroachdb/_index.md
  content/patterns/connected-vehicle-architecture/_index.md
  content/patterns/devsecops/_index.md
  content/patterns/emerging-disease-detection/_index.adoc
  content/patterns/hypershift/_index.adoc
  content/patterns/industrial-edge/_index.md
  content/patterns/kong-gateway/_index.md
  content/patterns/medical-diagnosis/_index.adoc
  content/patterns/mlops-fraud-detection/_index.adoc
  content/patterns/multicloud-gitops-Portworx/_index.md
  content/patterns/multicloud-gitops/_index.adoc
  content/patterns/retail/_index.md
  layouts/partials/menu-patterns-browser.html
Labels: lgtm, size/M

#388 speakerdeck
  modules/mcg-architecture.adoc
Labels: size/XS

#386 Blog about private repositories
  content/blog/2023-12-20-private-repos.md
Labels: size/M

#390 Pattern Review Update
  content/contribute/support-policies.adoc
  content/patterns/medical-diagnosis/_index.adoc
  content/patterns/medical-diagnosis/demo-script.adoc
  static/images/medical-edge/admin_developer-contexts.png
  static/images/medical-edge/aiml_pipeline.png
  static/images/medical-edge/image-generator-scale.png
  static/images/medical-edge/image-generator.png
Labels: lgtm, size/L

#387 Creating new Understanding namespaces blog
  content/blog/2023-12-15-understanding-namespaces.md
Labels: lgtm, size/L

#391 Industrial Edge demo-script
  content/patterns/industrial-edge/_index.md
  content/patterns/industrial-edge/demo-script.md
  static/images/industrial-edge/ie_argoApps.png
  static/images/industrial-edge/iot_dashboard.png
  static/images/industrial-edge/rerun_seed_pipeline.png
  static/images/industrial-edge/seed_pipeline.png
Labels: size/L

#392 Ie update
  content/patterns/industrial-edge/demo-script.md
Labels: size/S
