Repository validatedpatterns/docs, pull requests merged in 2024-06, with the labels that each got.

#426 rag llm docs update
  content/patterns/rag-llm-gitops/GPU_provisioning.md
  content/patterns/rag-llm-gitops/_index.md
  static/images/rag-llm-gitops/add_provider.png
  static/images/rag-llm-gitops/application.png
  static/images/rag-llm-gitops/chatgpt.png
  static/images/rag-llm-gitops/diagram.png
  static/images/rag-llm-gitops/gpt_response.png
  static/images/rag-llm-gitops/monitoring.png
  static/images/rag-llm-gitops/node-feature-discovery.png
  static/images/rag-llm-gitops/proposal.png
  static/images/rag-llm-gitops/rag-llm.png
  static/images/rag-llm-gitops/ragllm-application-running.png
  static/images/rag-llm-gitops/ragllm-application_route.png
  static/images/rag-llm-gitops/ragllm-grafana.png
  static/images/rag-llm-gitops/ragllm-label-nodes.png
  static/images/rag-llm-gitops/ragllm-model-application.png
  static/images/rag-llm-gitops/ragllm-nfd-instance.png
  static/images/rag-llm-gitops/ragllm-nfd-operator.png
  static/images/rag-llm-gitops/ragllm-nvidia-clusterpolicies.png
  static/images/rag-llm-gitops/ragllm-nvidia-operator.png
  static/images/rag-llm-gitops/ragllm-pattern-running-pods.png
  static/images/rag-llm-gitops/routes.png
Labels: size/L

#433 Moving demo/install content to getting-started doc
  content/patterns/rag-llm-gitops/_index.md
  content/patterns/rag-llm-gitops/getting-started.md
Labels: size/L

#436 Removing rhel-for-edge-general-sizing.adoc
  content/learn/rhel-for-edge-general-sizing.adoc
Labels: size/S

#437 Rename content dir for travelops pattern
  content/patterns/travelops/_index.adoc
  content/patterns/travelops/demo-script.adoc
  content/patterns/travelops/getting-started.adoc
  content/patterns/travelops/ideas-for-customization.adoc
Labels: size/XS

#432 Added clustergroup information in values files
  content/learn/clustergroup-in-values-files.adoc
  modules/applications-configuration-in-a-clustergroup.adoc
  modules/basic-parameters-configuration-in-a-clustergroup.adoc
  modules/imperative-values-configuration-in-a-clustergroup.adoc
  modules/managed-clustergroups-configuration-in-a-clustergroup.adoc
  modules/namespace-configuration-in-a-clustergroup.adoc
  modules/subscriptions-configuration-in-a-clustergroup.adoc
Labels: size/L

#438 Add placeholder for AGOF
  content/patterns/ansible-gitops-framework/_index.md
Labels: size/M

#435 Added information related to managing secrets in values files
  content/learn/secrets-management-in-the-Validated-Patterns-framework.adoc
  content/learn/secrets.adoc
  content/learn/vault.adoc
  modules/basic-secrets-configuration-in-a-clustergroup.adoc
  modules/letsencrypt-secrets-configuration-in-a-clustergroup.adoc
  modules/secret-store-configuration-in-a-clustergroup.adoc
Labels: size/XL

#439 Pattern GH Org Update
  content/patterns/rag-llm-gitops/_index.md
Labels: size/XS

#441 Increasing the timeout for 'hugo serve'
  config.yaml
Labels: size/XS
