Repository validatedpatterns/docs, pull requests merged in 2024-04, with the labels that each got.

#405 TELCODOCS-1595:Added values files information
  content/learn/values-files.adoc
  modules/about-values-files.adoc
  modules/outline-of-a-basic-values-file.adoc
Labels: lgtm, jira/valid-reference, size/M, ok-to-test

#421 Intel QAT accelerated Multicloud GitOps pattern
  content/patterns/multicloud-gitops-qat/_index.adoc
  content/patterns/multicloud-gitops-qat/mcg-qat-cluster-sizing.adoc
  content/patterns/multicloud-gitops-qat/mcg-qat-getting-started.adoc
  content/patterns/multicloud-gitops-qat/mcg-qat-ideas-for-customization.adoc
  content/patterns/multicloud-gitops-qat/mcg-qat-imperative-actions.adoc
  content/patterns/multicloud-gitops-qat/mcg-qat-managed-cluster.adoc
  modules/comm-attributes.adoc
  static/images/logos/intel-qat.png
  static/images/multicloud-gitops-qat/hybrid-multicloud-management-gitops-hl-arch.png
  static/images/multicloud-gitops-qat/logical-diagram.png
  static/images/multicloud-gitops-qat/multicloud-gitops-argocd-qat.png
  static/images/multicloud-gitops-qat/qat-create-pattern.png
  static/images/multicloud-gitops-qat/qat-ingress-log.png
  static/images/multicloud-gitops-qat/qat-installed-operators.png
  static/images/multicloud-gitops-qat/qat-logical-diagram.png
  static/images/multicloud-gitops-qat/qat-secret-vault.png
  static/images/multicloud-gitops-qat/qat-validated-pattern-operator.png
  static/images/multicloud-gitops-qat/schema-gitops.png
  static/images/multicloud-gitops-qat/schema-monitoring.png
  static/images/multicloud-gitops-qat/spi-multi-cloud-gitops-sd-gitops.png
  static/images/multicloud-gitops-qat/spi-multi-cloud-gitops-sd-install.png
  static/images/multicloud-gitops-qat/spi-multi-cloud-gitops-sd-monitoring.png
  static/images/multicloud-gitops-qat/spi-multi-cloud-gitops-sd-security.png
Labels: ok-to-test, size/XL

#425 fix docs ie
  content/patterns/industrial-edge/application.md
  content/patterns/industrial-edge/demo-script.md
Labels: size/S
