Repository validatedpatterns/docs, pull requests merged in 2024-01, with the labels that each got.

#395 issue 333
  content/patterns/multicloud-gitops-Portworx/_index.md
  modules/mcg-about-multicloud-gitops.adoc
Labels: size/XS

#398 New Cisco and Validated Patterns team partnership blog
  content/blog/2024-01-16-deploying-mcg-with-cisco-flashstack-portworx.md
Labels: lgtm, size/S

#396 Create badges directly from the JSON contents
  static/js/dashboard.v2.js
Labels: lgtm, size/L

#400 Fix demo script medical
  content/patterns/medical-diagnosis/demo-script.adoc
Labels: size/XS

#401 demo script mcg
  content/patterns/multicloud-gitops/mcg-demo-script.adoc
  modules/mcg-architecture.adoc
  static/images/multicloud-gitops/config-demo-patched.png
  static/images/multicloud-gitops/config-demo.png
  static/images/multicloud-gitops/hello-world.png
  static/images/multicloud-gitops/hub-argocd.png
  static/images/multicloud-gitops/network-routes.png
  static/images/multicloud-gitops/nine-box.png
Labels: size/L

#402 Document the need for aws-creds in AEG
  content/patterns/ansible-edge-gitops/getting-started.md
Labels: size/S
