Repository validatedpatterns/docs, pull requests merged in 2024-07, with the labels that each got.

#442 Gitea blog post
  .wordlist.txt
  Makefile
  content/blog/2024-07-12-in-cluster-git.md
  static/images/gitea-argocd-application.png
  static/images/gitea-console-link.png
  static/images/gitea-repository-list.png
  static/images/gitea-repository-show.png
  static/images/operator-gitea-config.png
Labels: lgtm, size/L

#444 Add Blog entry for writing kubeconfig files
  content/blog/2024-07-19-write-token-kubeconfig.md
Labels: size/M

#443 OPEA QnA chat Intel Gaudi pattern
  content/patterns/gaudi-rag-chat-qna/_index.adoc
  content/patterns/gaudi-rag-chat-qna/gaudi-rag-chat-qna-getting-started.adoc
  content/patterns/gaudi-rag-chat-qna/gaudi-rag-chat-qna-required-hardware.adoc
  content/patterns/gaudi-rag-chat-qna/gaudi-rag-chat-qna-troubleshooting.adoc
  modules/comm-attributes.adoc
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-add-data-connection.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-argocd.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-choose-project.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-create-single-model-serving.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-create-workbench.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-data-connection-details.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-deploy-model-1.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-deploy-model-2.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-deploy-notebook-1.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-deploy-notebook-2.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-notebook-view.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-tgi-status.png
  static/images/gaudi-rag-chat-qna/gaudi-rag-chat-qna-vp-overview.png
Labels: ok-to-test, size/XL
