Repository validatedpatterns/docs, pull requests merged in 2024-11, with the labels that each got.

#490 Initial pattern docs for ansible-edge-gitops-kasten
  .wordlist.txt
  content/patterns/ansible-edge-gitops-kasten/_index.md
  content/patterns/ansible-edge-gitops-kasten/ansible-automation-platform.md
  content/patterns/ansible-edge-gitops-kasten/cluster-sizing.md
  content/patterns/ansible-edge-gitops-kasten/getting-started.md
  content/patterns/ansible-edge-gitops-kasten/ideas-for-customization.md
  content/patterns/ansible-edge-gitops-kasten/installation-details.md
  content/patterns/ansible-edge-gitops-kasten/openshift-virtualization.md
  content/patterns/ansible-edge-gitops-kasten/troubleshooting.md
  content/patterns/ansible-edge-gitops-kasten/veeam-kasten.md
  static/images/ansible-edge-gitops-kasten/aeg-applications.png
  static/images/ansible-edge-gitops-kasten/aeg-arch-schematic.png
  static/images/ansible-edge-gitops-kasten/aeg-console-vm-template-1.png
  static/images/ansible-edge-gitops-kasten/aeg-ignition-kiosk-console.png
  static/images/ansible-edge-gitops-kasten/aeg-kubevirt411-con-ignition.png
  static/images/ansible-edge-gitops-kasten/aeg-new-operators.png
  static/images/ansible-edge-gitops-kasten/aeg-open-vm-console.png
  static/images/ansible-edge-gitops-kasten/aeg-openshift-vm-console.png
  static/images/ansible-edge-gitops-kasten/aeg-openshift-vm-screen.png
  static/images/ansible-edge-gitops-kasten/aeg-operators.png
  static/images/ansible-edge-gitops-kasten/aeg-show-vms.png
  static/images/ansible-edge-gitops-kasten/aeg-vm-ignition-intro.png
  static/images/ansible-edge-gitops-kasten/aeg-vm-unschedulable.png
  static/images/ansible-edge-gitops-kasten/ansible-edge-gitops-arch.png
  static/images/ansible-edge-gitops-kasten/automates-june-2022-deck-thumb.png
  static/images/ansible-edge-gitops-kasten/automates-june-2022-video-thumb.png
  static/images/ansible-edge-gitops-kasten/console-vm-spinning-up.png
  static/images/ansible-edge-gitops-kasten/console-vm-template-wizard-success.png
  static/images/ansible-edge-gitops-kasten/console-vm-template-wizard.png
  static/images/ansible-edge-gitops-kasten/kasten-login.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-policy-1.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-policy-2.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-policy-2b.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-policy-3.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-policy-4.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-policy-5.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-policy-6.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-policy-7.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-policy-8.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-policy-9.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-restore-1.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-restore-2.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-restore-3.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-restore-4.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-restore-5.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-restore-6.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-restore-7.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-runonce-1.png
  static/images/ansible-edge-gitops-kasten/kasten-operations-runonce-2.png
  static/images/ansible-edge-gitops-kasten/kasten-tour-applications.png
  static/images/ansible-edge-gitops-kasten/kasten-tour-dashboard-actiondetails.png
  static/images/ansible-edge-gitops-kasten/kasten-tour-dashboard-activity.png
  static/images/ansible-edge-gitops-kasten/kasten-tour-dashboard-widgets.png
  static/images/ansible-edge-gitops-kasten/kasten-tour-policies.png
  static/images/ansible-edge-gitops-kasten/kasten-tour-profiles.png
  static/images/ansible-edge-gitops-kasten/ocp-console-aap-admin-password-detail.png
  static/images/ansible-edge-gitops-kasten/ocp-console-secrets-aap-admin-password.png
  static/images/logos/veeam-kasten.png
Labels: needs-ok-to-test, size/XXL, ok-to-test

#491 New blog post about how to sequence subscriptions
  content/blog/2024-11-07-clustergroup-sequencing.adoc
Labels: size/L

#492 Clean up blog post
  content/blog/2024-11-07-clustergroup-sequencing.adoc
Labels: size/S

#482 feat: Coco pattern documentation
  content/patterns/coco-pattern/_index.adoc
  content/patterns/coco-pattern/coco-pattern-azure-requirements.adoc
  content/patterns/coco-pattern/coco-pattern-getting-started.adoc
  static/images/coco-pattern/isolation.png
  static/images/coco-pattern/overview-schematic.png
  static/images/coco-pattern/peer_pods.png
  static/images/coco-pattern/trustee.png
  static/images/logos/coco-logo.png
Labels: needs-ok-to-test, size/L

#493 Update blog post to also mention applications
  content/blog/2024-11-07-clustergroup-sequencing.adoc
Labels: size/S

#481 RegionalDR VP docs
  content/patterns/regional-dr/_index.md
  static/images/logos/regional-dr.png
  static/images/regional-resiliency-pattern/architecture-diagram-vp-regional-dr-v6.png
  static/images/regional-resiliency-pattern/logical-architecture-diagram-vp-regional-dr-v6.png
Labels: needs-ok-to-test, size/L

#495 Switch htmltest to be run in cron
  .github/workflows/htmltest.yml
Labels: size/XS

#498 Update _index.md
  content/patterns/ansible-edge-gitops-kasten/_index.md
Labels: size/XS, ok-to-test

#497 Update Veeam pattern name and getting started steps
  content/patterns/ansible-edge-gitops-kasten/_index.md
  content/patterns/ansible-edge-gitops-kasten/getting-started.md
Labels: size/M, ok-to-test

#496 Updated the document with model configuration
  content/patterns/rag-llm-gitops/_index.md
  content/patterns/rag-llm-gitops/getting-started.md
Labels: lgtm, needs-ok-to-test, size/M

#489 TELCODOCS-2082 VP Quick start guide redo
  content/learn/getting-started-multi-cloud-gitops.adoc
  content/learn/getting-started-secret-management.adoc
  content/learn/importing-a-cluster.adoc
  content/learn/quickstart.adoc
  content/learn/validated_patterns_frameworks.adoc
  content/learn/vp_agof.adoc
  content/patterns/ansible-gitops-framework/_index.md
  static/images/multicloud-gitops/config-demo-mysecret.png
Labels: size/XL

#499 Fix 404 link for subscriptions in agof
  content/learn/vp_agof.adoc
Labels: size/XS

#502 Drop the note about IE and 4.14 clusters now that IE 2.0 has merged
  content/ci/_index.md
Labels: size/XS

#501 Patterns browser v2
  content/patterns/ansible-edge-gitops-kasten/_index.md
  content/patterns/cockroachdb/_index.md
  content/patterns/coco-pattern/_index.adoc
  content/patterns/connected-vehicle-architecture/_index.md
  content/patterns/kong-gateway/_index.md
  content/patterns/multicloud-gitops-Portworx/_index.md
  layouts/partials/menu-patterns-browser.html
  layouts/partials/patterns-browser.html
  layouts/patterns/list.json.json
  static/js/patterns-browser-v2.js
Labels: size/L

#504 Adding missing attributes
  modules/comm-attributes.adoc
Labels: size/XS
