Repository validatedpatterns/docs, pull requests merged in 2024-05, with the labels that each got.

#428 OpenShift AI Pattern Docs
  content/patterns/openshift-ai/_index.adoc
  content/patterns/openshift-ai/getting-started.adoc
  modules/rhoai-about.adoc
  modules/rhoai-architecture.adoc
  modules/rhoai-deploying.adoc
  static/images/rhoai/rhoai-drawio-logical.png
  static/images/rhoai/rhods-ai_dashboard.png
  static/images/rhoai/rhods-application_menu.png
  static/images/rhoai/rhods-dashboard_route.png
  static/images/rhoai/rhods-installed_operators.png
  static/images/rhoai/rhods-ocgetapps.png
  static/images/rhoai/rhods-sync-success.png
Labels: size/L

#427 Fix for newer hugo versions
  content/patterns/mlops-fraud-detection/_index.adoc
Labels: lgtm, size/XS

#429 Improve the usability of pre-release badges
  layouts/partials/menu-ci.html
  static/js/dashboard.v2.js
Labels: size/M

#430 make spellcheck
  .spellcheck.yml
  .wordlist.txt
  Makefile
  content/blog/2023-11-17-argo-configmanagement-plugins.md
  content/blog/2024-01-26-more-secrets-options.md
  content/blog/2024-02-07-hcp-htpasswd-config.md
  content/learn/test-artefacts.adoc
  content/patterns/medical-diagnosis-amx/getting-started.adoc
  content/patterns/medical-diagnosis/demo-script.adoc
  content/patterns/multicloud-gitops-amx-rhoai/_index.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-bert-script.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-demo-script.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-imperative-actions.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-managed-cluster.adoc
  content/patterns/multicloud-gitops-amx/mcg-amx-getting-started.adoc
  content/patterns/multicloud-gitops-amx/mcg-amx-imperative-actions.adoc
  content/patterns/multicloud-gitops-amx/mcg-amx-managed-cluster.adoc
  content/patterns/multicloud-gitops-qat/mcg-qat-getting-started.adoc
  content/patterns/multicloud-gitops-qat/mcg-qat-imperative-actions.adoc
  content/patterns/multicloud-gitops-qat/mcg-qat-managed-cluster.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/_index.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-demo-script.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-getting-started.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-imperative-actions.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-managed-cluster.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-demo-script.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-getting-started.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-imperative-actions.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-managed-cluster.adoc
  content/patterns/multicloud-gitops/mcg-demo-script.adoc
Labels: lgtm, size/XXL
