Repository validatedpatterns/docs, pull requests merged in 2024-10, with the labels that each got.

#483 fix: Make it clear you need ascii doctor
  README.md
Labels: lgtm, size/S, ok-to-test

#485 fix: support make serve on mac os
  Makefile
Labels: size/S, ok-to-test

#487 Disconnected blog post
  .wordlist.txt
  content/blog/2024-09-13-using-hypershift.adoc
  content/blog/2024-09-26-slimming-of-common.adoc
  content/blog/2024-10-12-disconnected.adoc
Labels: size/L

#469 Added overview of validated patterns and removed the old content
  content/learn/about-validated-patterns.adoc
  content/learn/about.adoc
Labels: size/L

#470 Moved patterns tier info under about validated patterns section
  content/learn/about-pattern-tiers-types.adoc
Labels: size/XS

#363 Adding links to see page history and report doc bugs
  layouts/partials/toc.html
Labels: size/S

#477 TELCODOCS-2000 documenting the AGOF 2
  content/learn/vp_agof.adoc
  content/learn/vp_agof_config_controller.adoc
Labels: lgtm, size/XL

#488 Improve blog post
  content/blog/2024-09-26-slimming-of-common.adoc
Labels: size/XS
