Repository validatedpatterns/docs, pull requests merged in 2024-03, with the labels that each got.

#414 Update 2024-03-05-intel-accelerated-patterns.md
  content/blog/2024-03-05-intel-accelerated-patterns.md
Labels: lgtm, needs-ok-to-test, size/XS

#418 Intel SGX protected application in Multicloud GitOps pattern
  content/patterns/multicloud-gitops-sgx-hello-world/_index.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-cluster-sizing.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-demo-script.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-getting-started.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-ideas-for-customization.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-imperative-actions.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-managed-cluster.adoc
  modules/comm-attributes.adoc
  modules/intel-recommended-cluster-sizing-5th-gen-sgx.adoc
  static/images/logos/sgx-intel-ai.png
  static/images/multicloud-gitops-sgx-hello-world/config-demo-patched.png
  static/images/multicloud-gitops-sgx-hello-world/config-demo.png
  static/images/multicloud-gitops-sgx-hello-world/hello-world-sgx-logs.png
  static/images/multicloud-gitops-sgx-hello-world/hello-world.png
  static/images/multicloud-gitops-sgx-hello-world/hub-argocd.png
  static/images/multicloud-gitops-sgx-hello-world/hybrid-multicloud-management-gitops-hl-arch.png
  static/images/multicloud-gitops-sgx-hello-world/multicloud-gitops-argocd-sgx.png
  static/images/multicloud-gitops-sgx-hello-world/network-routes.png
  static/images/multicloud-gitops-sgx-hello-world/nine-box.png
  static/images/multicloud-gitops-sgx-hello-world/schema-gitops.png
  static/images/multicloud-gitops-sgx-hello-world/schema-monitoring.png
  static/images/multicloud-gitops-sgx-hello-world/sgx-create-pattern.png
  static/images/multicloud-gitops-sgx-hello-world/sgx-installed-operators.png
  static/images/multicloud-gitops-sgx-hello-world/sgx-logical-diagram.png
  static/images/multicloud-gitops-sgx-hello-world/sgx-secret-vault.png
  static/images/multicloud-gitops-sgx-hello-world/sgx-validated-pattern-operator.png
  static/images/multicloud-gitops-sgx-hello-world/spi-multi-cloud-gitops-sd-gitops.png
  static/images/multicloud-gitops-sgx-hello-world/spi-multi-cloud-gitops-sd-install.png
  static/images/multicloud-gitops-sgx-hello-world/spi-multi-cloud-gitops-sd-monitoring.png
  static/images/multicloud-gitops-sgx-hello-world/spi-multi-cloud-gitops-sd-security.png
Labels: size/XXL, ok-to-test

#417 Update 2024-03-05-intel-accelerated-patterns.md
  content/blog/2024-03-05-intel-accelerated-patterns.md
Labels: needs-ok-to-test, size/XS

#420 Intel AMX accelerated Multicloud GitOps pattern with OpenShift AI
  content/patterns/multicloud-gitops-amx-rhoai/_index.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-bert-script.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-cluster-sizing.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-demo-script.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-getting-started.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-ideas-for-customization.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-imperative-actions.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-managed-cluster.adoc
  modules/comm-attributes.adoc
  modules/intel-recommended-cluster-sizing-5th-gen-amx.adoc
  static/images/multicloud-gitops-amx-rhoai/amx-rhoai-bert-logs.png
  static/images/multicloud-gitops-amx-rhoai/amx-rhoai-create-pattern.png
  static/images/multicloud-gitops-amx-rhoai/amx-rhoai-installed-operators.png
  static/images/multicloud-gitops-amx-rhoai/amx-rhoai-logical-diagram.png
  static/images/multicloud-gitops-amx-rhoai/amx-rhoai-secret-vault.png
  static/images/multicloud-gitops-amx-rhoai/amx-rhoai-validated-pattern-operator-1.png
  static/images/multicloud-gitops-amx-rhoai/amx-rhoai-validated-pattern-operator-2.png
  static/images/multicloud-gitops-amx-rhoai/config-demo-patched.png
  static/images/multicloud-gitops-amx-rhoai/config-demo.png
  static/images/multicloud-gitops-amx-rhoai/hello-world.png
  static/images/multicloud-gitops-amx-rhoai/hub-argocd.png
  static/images/multicloud-gitops-amx-rhoai/hybrid-multicloud-management-gitops-hl-arch.png
  static/images/multicloud-gitops-amx-rhoai/logical-diagram.png
  static/images/multicloud-gitops-amx-rhoai/multicloud-gitops-argocd-amx-rhoai.png
  static/images/multicloud-gitops-amx-rhoai/network-routes.png
  static/images/multicloud-gitops-amx-rhoai/nine-box.png
  static/images/multicloud-gitops-amx-rhoai/schema-gitops.png
  static/images/multicloud-gitops-amx-rhoai/schema-monitoring.png
  static/images/multicloud-gitops-amx-rhoai/spi-multi-cloud-gitops-sd-gitops.png
  static/images/multicloud-gitops-amx-rhoai/spi-multi-cloud-gitops-sd-install.png
  static/images/multicloud-gitops-amx-rhoai/spi-multi-cloud-gitops-sd-monitoring.png
  static/images/multicloud-gitops-amx-rhoai/spi-multi-cloud-gitops-sd-security.png
Labels: ok-to-test, size/XL

#419 Introduce Vault component protected with Intel Secure Guard Extensions (SGX)
  content/patterns/medical-diagnosis-amx/cluster-sizing.adoc
  content/patterns/multicloud-gitops-amx/mcg-amx-cluster-sizing.adoc
  content/patterns/multicloud-gitops-amx/mcg-amx-getting-started.adoc
  content/patterns/multicloud-gitops-sgx/_index.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-cluster-sizing.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-demo-script.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-getting-started.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-ideas-for-customization.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-imperative-actions.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-managed-cluster.adoc
  modules/intel-recommended-cluster-sizing-4th-gen.adoc
  static/images/multicloud-gitops-sgx/config-demo-patched.png
  static/images/multicloud-gitops-sgx/config-demo.png
  static/images/multicloud-gitops-sgx/hello-world.png
  static/images/multicloud-gitops-sgx/hub-argocd.png
  static/images/multicloud-gitops-sgx/hybrid-multicloud-management-gitops-hl-arch.png
  static/images/multicloud-gitops-sgx/logical-diagram.png
  static/images/multicloud-gitops-sgx/multicloud-gitops-argocd-sgx.png
  static/images/multicloud-gitops-sgx/network-routes.png
  static/images/multicloud-gitops-sgx/nine-box.png
  static/images/multicloud-gitops-sgx/schema-gitops.png
  static/images/multicloud-gitops-sgx/schema-monitoring.png
  static/images/multicloud-gitops-sgx/sgx-create-pattern.png
  static/images/multicloud-gitops-sgx/sgx-installed-operators.png
  static/images/multicloud-gitops-sgx/sgx-logical-diagram.png
  static/images/multicloud-gitops-sgx/sgx-secret-vault.png
  static/images/multicloud-gitops-sgx/sgx-validated-patter-operator.png
  static/images/multicloud-gitops-sgx/sgx-validated-pattern-operator.png
  static/images/multicloud-gitops-sgx/spi-multi-cloud-gitops-sd-gitops.png
  static/images/multicloud-gitops-sgx/spi-multi-cloud-gitops-sd-install.png
  static/images/multicloud-gitops-sgx/spi-multi-cloud-gitops-sd-monitoring.png
  static/images/multicloud-gitops-sgx/spi-multi-cloud-gitops-sd-security.png
Labels: size/XXL, ok-to-test
