Repository validatedpatterns/docs, pull requests merged in 2024-08, with the labels that each got.

#445 ragllm edb docs update
  content/patterns/rag-llm-gitops/_index.md
  content/patterns/rag-llm-gitops/getting-started.md
  static/images/rag-llm-gitops/diagram-edb.png
  static/images/rag-llm-gitops/diagram.png
  static/images/rag-llm-gitops/launch-application.png
  static/images/rag-llm-gitops/launch-grafana.png
  static/images/rag-llm-gitops/nodes.png
  static/images/rag-llm-gitops/rag-llm-pgvector.png
Labels: size/L

#446 Update link to Red Hat Architecture
  content/patterns/medical-diagnosis/_index.adoc
Labels: size/XS, ok-to-test

#440 TELCODOCS-1905 Validated Patterns Key Concepts - Part 1
  content/learn/importing-a-cluster.adoc
  content/learn/infrastructure.adoc
  content/learn/keyconcepts.adoc
  content/learn/ocp-cluster-general-sizing.adoc
  content/learn/quickstart.adoc
  content/learn/secrets.adoc
  content/learn/values-files.adoc
  content/learn/workflow.adoc
  modules/about-values-files.adoc
Labels: size/L

#450 Update link to Red Hat Architecture
  content/patterns/medical-diagnosis-amx/_index.adoc
Labels: size/XS, ok-to-test

#449 Update link to Red Hat Architecture
  content/patterns/emerging-disease-detection/_index.adoc
Labels: size/XS, ok-to-test

#448 Update link to Red Hat Architecture
  content/patterns/industrial-edge/_index.md
Labels: size/XS, ok-to-test

#453 Gitea no mirror
  content/blog/2024-07-12-in-cluster-git.md
Labels: size/S

#452 Auto-generation of JSON file for all pattern params
  config.yaml
  content/patterns/_index.md
  layouts/patterns/list.json.json
Labels: size/S

#431 hugo upgrade
  .github/workflows/gh-pages.yml
Labels: size/XS

#455 Fix a bunch of spellcheck errors
  .wordlist.txt
  content/blog/2024-07-12-in-cluster-git.md
  content/patterns/gaudi-rag-chat-qna/_index.adoc
  content/patterns/gaudi-rag-chat-qna/gaudi-rag-chat-qna-getting-started.adoc
  content/patterns/rag-llm-gitops/GPU_provisioning.md
  content/patterns/rag-llm-gitops/getting-started.md
Labels: size/M

#456 Pushsecrets blog post
  .wordlist.txt
  content/blog/2024-08-30-push-secrets.md
Labels: size/M
