Repository validatedpatterns/docs, pull requests merged in 2024-02, with the labels that each got.

#378 Update with new VP link
  modules/mfd-about-mlops-fraud-detection.adoc
Labels: size/XS

#403 Secrets blog
  content/blog/2024-01-26-more-secrets-options.md
Labels: size/L

#404 htpass + hcp oauth config
  content/blog/2024-02-07-hcp-htpasswd-config.md
Labels: size/L

#406 travelops documentation
  content/patterns/travelops-ossm/_index.adoc
  content/patterns/travelops-ossm/demo-script.adoc
  content/patterns/travelops-ossm/getting-started.adoc
  content/patterns/travelops-ossm/ideas-for-customization.adoc
  modules/comm-attributes.adoc
  modules/trvlops-about-customizing-pattern.adoc
  modules/trvlops-about.adoc
  modules/trvlops-architecture.adoc
  modules/trvlops-demo.adoc
  modules/trvlops-deploying.adoc
  static/images/travelops/kiali-db.png
  static/images/travelops/ossm-arch-travelops.png
  static/images/travelops/ossm-kiali-db-arrows.png
  static/images/travelops/ossm-kiali-db.jpg
  static/images/travelops/ossm-kiali.png
  static/images/travelops/ossm-sync-success.png
  static/images/travelops/ossm-travelops-controlapp.png
  static/images/travelops/travel-agency-svc-kiali.png
Labels: size/L

#409 updated alias for medical-diagnosis-amx docs
  content/patterns/medical-diagnosis-amx/cluster-sizing.adoc
  content/patterns/medical-diagnosis-amx/getting-started.adoc
  content/patterns/medical-diagnosis-amx/ideas-for-customization.adoc
  content/patterns/medical-diagnosis-amx/troubleshooting.adoc
Labels: size/S

#412 Note known issue on 4.14
  content/ci/_index.md
Labels: size/XS
