Repository validatedpatterns/docs, pull requests merged in 2024-09, with the labels that each got.

#458 Clean up some syntax in Key Concepts
  content/learn/keyconcepts.adoc
Labels: size/M, ok-to-test

#460 Fix multiple docs and testing problems
  .htmltest.yml
  content/contribute/creating-a-pattern.adoc
  content/learn/importing-a-cluster.adoc
  content/learn/test-artifacts.adoc
  content/learn/tested.adoc
  content/learn/vault.adoc
  content/patterns/gaudi-rag-chat-qna/gaudi-rag-chat-qna-required-hardware.adoc
  content/patterns/medical-diagnosis-amx/cluster-sizing.adoc
  content/patterns/medical-diagnosis-amx/getting-started.adoc
  content/patterns/medical-diagnosis/_index.adoc
  content/patterns/medical-diagnosis/cluster-sizing.adoc
  content/patterns/medical-diagnosis/demo-script.adoc
  content/patterns/medical-diagnosis/getting-started.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-bert-script.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-demo-script.adoc
  content/patterns/multicloud-gitops-amx/_index.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-demo-script.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-demo-script.adoc
  content/patterns/multicloud-gitops/mcg-demo-script.adoc
  modules/edd-using-edd-pattern.adoc
  modules/mfd-using-mfd-demo.adoc
Labels: size/L, ok-to-test

#461 Align htmltest versions with homepage-container
  .github/workflows/htmltest.yml
Labels: size/XS, ok-to-test

#457 docs: add EDB to the `rag-llm-gitops` validated pattern
  content/patterns/rag-llm-gitops/_index.md
  content/patterns/rag-llm-gitops/getting-started.md
Labels: lgtm, needs-ok-to-test, size/M

#462 Fix pattern filtering
  layouts/partials/menu-patterns-browser.html
Labels: lgtm, size/S, ok-to-test

#447 Portfolio2Solution Architecture Display update
  layouts/partials/links.html
Labels: size/XS

#466 Fix local htmltest
  .htmltest.yml
Labels: size/XS

#451 TELCODOCS-1999 Documentation for VP OpenShift Framework
  content/contribute/structure.adoc
  content/learn/about-pattern-tiers-types.adoc
  content/learn/faq.adoc
  content/learn/implementation.adoc
  content/learn/importing-a-cluster.adoc
  content/learn/infrastructure.adoc
  content/learn/keyconcepts.adoc
  content/learn/maintained.adoc
  content/learn/quickstart.adoc
  content/learn/sandbox.adoc
  content/learn/secrets.adoc
  content/learn/tested.adoc
  content/learn/using-validated-pattern-operator.adoc
  content/learn/validated_patterns_frameworks.adoc
  content/learn/values-files.adoc
  content/learn/vp_openshift_framework.adoc
  content/learn/vp_structure_vp_pattern.adoc
  content/learn/workflow.adoc
Labels: size/XL

#468 fix htmltest
  .github/workflows/htmltest.yml
  Makefile
  content/contribute/creating-a-pattern.adoc
Labels: size/S

#472 Fix a few 404
  content/blog/2022-12-01-multicluster-devsecops.md
  content/blog/2023-12-15-understanding-namespaces.md
  content/learn/implementation.adoc
  content/patterns/ansible-edge-gitops/installation-details.md
Labels: size/S

#471 Update documentation for 5th Gen Intel Xeon, update links and minor adjustments
  content/patterns/ansible-edge-gitops/getting-started.md
  content/patterns/gaudi-rag-chat-qna/gaudi-rag-chat-qna-getting-started.adoc
  content/patterns/medical-diagnosis-amx/_index.adoc
  content/patterns/medical-diagnosis-amx/cluster-sizing.adoc
  content/patterns/medical-diagnosis-amx/getting-started.adoc
  content/patterns/medical-diagnosis/cluster-sizing.adoc
  content/patterns/medical-diagnosis/getting-started.adoc
  content/patterns/multicloud-gitops-amx-rhoai/_index.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-cluster-sizing.adoc
  content/patterns/multicloud-gitops-amx-rhoai/mcg-amx-rhoai-getting-started.adoc
  content/patterns/multicloud-gitops-amx/_index.adoc
  content/patterns/multicloud-gitops-amx/mcg-amx-cluster-sizing.adoc
  content/patterns/multicloud-gitops-qat/_index.adoc
  content/patterns/multicloud-gitops-qat/mcg-qat-cluster-sizing.adoc
  content/patterns/multicloud-gitops-qat/mcg-qat-getting-started.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/_index.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/mcg-sgx-hello-world-cluster-sizing.adoc
  content/patterns/multicloud-gitops-sgx/_index.adoc
  content/patterns/multicloud-gitops-sgx/mcg-sgx-cluster-sizing.adoc
  modules/mcg-about-cluster-sizing.adoc
  static/images/medical-diagnosis-amx/gitops-view.png
  static/images/multicloud-gitops-amx-rhoai/amx-rhoai-installed-operators.png
  static/images/multicloud-gitops-amx-rhoai/multicloud-gitops-argocd-amx-rhoai.png
  static/images/multicloud-gitops-amx/amx-logical-diagram.png
Labels: size/M, ok-to-test

#474 Blog: Using HyperShift
  content/blog/2024-09-13-using-hypershift.adoc
Labels: size/L

#475 HyperShift Blog fixup
  content/blog/2024-09-13-using-hypershift.adoc
Labels: size/S

#476 Add toc, fix commands
  content/blog/2024-09-13-using-hypershift.adoc
Labels: size/XS

#479 Update rhoai-deploying.adoc
  modules/rhoai-deploying.adoc
Labels: lgtm, size/S

#478 Add a blog post explaining the slimming of common
  content/blog/2024-09-26-slimming-of-common.adoc
Labels: size/L

#480 Add some information how to develop in git
  content/blog/2024-09-26-slimming-of-common.adoc
Labels: size/M
