Repository validatedpatterns/docs, pull requests merged in 2024-12, with the labels that each got.

#505 fix: correct link
  content/patterns/openshift-ai/_index.adoc
Labels: lgtm, needs-ok-to-test, size/XS

#503 Add initial blog post for new IE rewrite
  content/blog/2024-12-02-industrial-edge-rewrite.adoc
  static/images/industrial-edge/gitea.png
  static/images/industrial-edge/jupyter.png
  static/images/industrial-edge/new-pipeline.png
  static/images/industrial-edge/nine-box.png
  static/images/industrial-edge/training-pipeline.png
  static/images/industrial-edge/training-pipeline2.png
Labels: size/M

#500 Divided the workflow content into separate learn and contribute sections
  content/contribute/contributing-and-managing-patterns.adoc
  content/learn/workflow.adoc
Labels: size/L

#508 Moved patterns from learn to contribute section
  content/contribute/implementation.adoc
  content/contribute/maintained.adoc
  content/contribute/sandbox.adoc
  content/contribute/test-artifacts.adoc
  content/contribute/tested.adoc
  content/learn/about-pattern-tiers-types.adoc
Labels: size/L
