Repository validatedpatterns/docs, pull requests merged in 2025-02, with the labels that each got.

#524 Extend cluster sizing template with notes
  modules/cluster-sizing-template.adoc
Labels: size/XS

#526 Merge cluster variables change for rag-llm-gitops
  modules/rag-llm-gitops/metadata-rag-llm-gitops.adoc
Labels: size/XS

#528 Merge cluster variables change for openshift-ai
  modules/openshift-ai/metadata-openshift-ai.adoc
Labels: size/S

#529 Medical diagnosis fixes
  content/patterns/medical-diagnosis/demo-script.adoc
  content/patterns/medical-diagnosis/getting-started.adoc
Labels: lgtm, size/M

#523 Expand supported regions
  content/patterns/rag-llm-gitops/getting-started.md
Labels: size/M

#517 TELCODOCS-2144 update industrial edge docs
  content/patterns/industrial-edge/_index.md
  content/patterns/industrial-edge/add-managed-cluster.md
  content/patterns/industrial-edge/application.md
  content/patterns/industrial-edge/getting-started.md
  content/patterns/industrial-edge/ideas-for-customization.md
  static/images/industrial-edge/datacenter-argocd-apps.png
  static/images/industrial-edge/gitea-commit-1.png
  static/images/industrial-edge/gitea-commit.png
  static/images/industrial-edge/gitea-edit.png
  static/images/industrial-edge/gitea-iot-edit.png
  static/images/industrial-edge/gitea-pipeline-pr.png
  static/images/industrial-edge/gitea-signin.png
  static/images/industrial-edge/network-routing-line-dashboard.png
  static/images/industrial-edge/nine-box.png
  static/images/industrial-edge/pipeline-iot-frontend.png
Labels: size/XL

#530 Add FEO docs
  content/blog/2025-01-09-AGOF_v2.adoc
  content/patterns/federated-edge-observability/_index.md
  content/patterns/federated-edge-observability/ansible-automation-platform.md
  content/patterns/federated-edge-observability/getting-started.md
  static/images/federated-edge-observability/FEO-applications.png
  static/images/federated-edge-observability/FEO-grafana.png
  static/images/federated-edge-observability/FEO-operators.png
  static/images/federated-edge-observability/FEO-vms.png
Labels: size/L

#531 Fix the urls being generated for patterns on the CI status page
  static/js/dashboard.v2.js
Labels: size/S

#532 Fix the ragllm ci entry
  content/patterns/rag-llm-gitops/_index.md
Labels: size/XS

#533 Fix the ie and openshiftai ci entry
  content/patterns/industrial-edge/_index.md
  content/patterns/openshift-ai/_index.adoc
Labels: size/XS

#534 Fix edd CI status
  content/patterns/emerging-disease-detection/_index.adoc
Labels: size/XS

#535 Merge cluster variables change for multicloud-gitops
  modules/multicloud-gitops/metadata-multicloud-gitops.adoc
Labels: size/M

#536 Switch mcg to use standard cluster sizing template
  content/patterns/multicloud-gitops/mcg-cluster-sizing.adoc
  modules/mcg-about-cluster-sizing.adoc
  modules/mcg-aws-instance-types.adoc
  modules/mcg-azure-instance-types.adoc
  modules/mcg-gcp-instance-types.adoc
  modules/mcg-hub-cluster-sizing.adoc
  modules/mcg-managed-cluster-sizing.adoc
  modules/mcg-support-matrix.adoc
Labels: size/L

#537 Corrected the example in clustergroup values files
  modules/subscriptions-configuration-in-a-clustergroup.adoc
Labels: size/XS

#538 Merge cluster variables change for openshift-ai
  modules/openshift-ai/metadata-openshift-ai.adoc
Labels: size/XS

#539 TELCODOCS-2157 Catching up with changes to common
  content/learn/keyconcepts.adoc
  content/learn/vp_openshift_framework.adoc
Labels: size/L

#541 Merge cluster variables change for medical-diagnosis
  modules/medical-diagnosis/metadata-medical-diagnosis.adoc
Labels: size/S

#542 Merge cluster variables change for ansible-edge-gitops
  modules/ansible-edge-gitops/metadata-ansible-edge-gitops.adoc
Labels: size/S

#544 Move to standardized cluster sizing template
  content/patterns/ansible-edge-gitops/cluster-sizing.adoc
  content/patterns/ansible-edge-gitops/cluster-sizing.md
Labels: size/L

#525 TELCODOCS-2198 Docs update for OpenShift AI
  content/patterns/openshift-ai/_index.adoc
  content/patterns/openshift-ai/ai-demo-app.adoc
  content/patterns/openshift-ai/cluster-sizing.adoc
  content/patterns/rag-llm-gitops/getting-started.md
  modules/rhoai-demo-app.adoc
  modules/rhoai-deploying.adoc
  static/images/rhoai/add-kaggle.png
  static/images/rhoai/git-clone-button.png
  static/images/rhoai/my-first-workbench.png
  static/images/rhoai/predict-step4.png
  static/images/rhoai/predict.png
  static/images/rhoai/prediction-dog-cat.png
  static/images/rhoai/rhods-application_menu.png
  static/images/rhoai/rhods-sync-success.png
Labels: size/XL

#540 TELCODOCS-2143 Updating Medical diags documentation rev2
  content/patterns/medical-diagnosis/_index.adoc
  content/patterns/medical-diagnosis/cluster-sizing.adoc
  content/patterns/medical-diagnosis/demo-script.adoc
  content/patterns/medical-diagnosis/getting-started.adoc
  content/patterns/medical-diagnosis/ideas-for-customization.adoc
  content/patterns/medical-diagnosis/troubleshooting.adoc
  static/images/medical-edge/medical-diags-overview.png
  static/images/medical-edge/storage-rgw-route.png
  static/images/medical-edge/storage-route.png
Labels: size/XL

#546 minor medical diagnosis pattern docs fixes
  content/patterns/medical-diagnosis/demo-script.adoc
  content/patterns/medical-diagnosis/getting-started.adoc
Labels: size/S

#547 Merge cluster variables change for federated-edge-observability
  modules/federated-edge-observability/metadata-federated-edge-observability.adoc
Labels: size/M

#545 Telcodocs 2203 updates to fed edge pattern docs
  content/patterns/federated-edge-observability/_index.adoc
  content/patterns/federated-edge-observability/_index.md
  content/patterns/federated-edge-observability/ansible-automation-platform.adoc
  content/patterns/federated-edge-observability/ansible-automation-platform.md
  content/patterns/federated-edge-observability/cluster-sizing.adoc
  content/patterns/federated-edge-observability/getting-started.adoc
  content/patterns/federated-edge-observability/getting-started.md
  modules/comm-attributes.adoc
  static/images/federated-edge-observability/FEO-applications.png
  static/images/federated-edge-observability/FEO-grafana-plotted.png
  static/images/federated-edge-observability/FEO-grafana.png
  static/images/federated-edge-observability/FEO-vms.png
  static/images/federated-edge-observability/app-login.png
  static/images/federated-edge-observability/ocp-console-aap-admin-password-detail.png
  static/images/federated-edge-observability/ocp-console-secrets-aap-admin-password.png
Labels: size/XL

#549 fixing minor display issues
  content/patterns/federated-edge-observability/getting-started.adoc
Labels: size/S

#550 add snippet about how to debug failures loading secrets
  content/learn/getting-started-secret-management.adoc
Labels: size/S

#551 Fix small typo
  content/learn/getting-started-secret-management.adoc
Labels: size/XS

#552 Telcodocs 2223
  content/contribute/creating-a-pattern.adoc
  content/learn/vp_add_ops_to_pattern.adoc
  content/learn/vp_add_specific_ops_to_pattern.adoc
Labels: size/L
