Repository validatedpatterns/docs, pull requests merged in 2025-01, with the labels that each got.

#511 Fix installation link
  content/patterns/coco-pattern/_index.adoc
Labels: size/XS

#512 Fix a couple of links
  content/blog/2022-10-12-acm-provisioning.md
  content/contribute/background-on-pattern-development.adoc
Labels: size/XS

#509 TELCODOCS-2146 Updating the multi-cloud GitOps pattern VP docs
  content/learn/getting-started-multi-cloud-gitops.adoc
  content/patterns/multicloud-gitops/_index.adoc
  content/patterns/multicloud-gitops/mcg-cluster-sizing.adoc
  content/patterns/multicloud-gitops/mcg-demo-script.adoc
  content/patterns/multicloud-gitops/mcg-getting-started.adoc
  content/patterns/multicloud-gitops/mcg-managed-cluster.adoc
  modules/comm-designate-cluster-as-managed-cluster-site.adoc
  modules/mcg-about-customizing-pattern.adoc
  modules/mcg-architecture.adoc
  modules/mcg-deploying-managed-cluster-using-rhacm.adoc
  modules/mcg-deploying-mcg-pattern.adoc
  modules/mcg-understanding-rhacm-requirements.adoc
  modules/mcg-using-imperative-actions.adoc
  static/images/multicloud-gitops/config-demo-degarded.png
  static/images/multicloud-gitops/multicloud-gitops-argocd.png
Labels: lgtm, size/XL

#513 Add a note about operators list and ocp versions
  content/patterns/industrial-edge/getting-started.md
Labels: size/XS

#514 Change oc scale command to follow pattern change
  content/patterns/medical-diagnosis/cluster-sizing.adoc
  content/patterns/medical-diagnosis/getting-started.adoc
  content/patterns/medical-diagnosis/troubleshooting.adoc
Labels: size/S

#415 Adding Author and Company field
  layouts/partials/authors.html
  layouts/partials/patterns-index.html
  static/images/logos/RHlogo.svg
Labels: size/M

#507 TELCODOCS-2134 updating AI pattern
  content/patterns/rag-llm-gitops/GPU_provisioning.md
  content/patterns/rag-llm-gitops/_index.md
  content/patterns/rag-llm-gitops/customize-demo-app.md
  content/patterns/rag-llm-gitops/deploying-different-db.md
  content/patterns/rag-llm-gitops/getting-started.md
  content/patterns/rag-llm-gitops/rating-the-provider.md
  static/images/rag-llm-gitops/add_provider-1.png
  static/images/rag-llm-gitops/add_provider-2.png
  static/images/rag-llm-gitops/add_provider-3.png
  static/images/rag-llm-gitops/add_provider.png
  static/images/rag-llm-gitops/application.png
  static/images/rag-llm-gitops/launch-application-main_menu.png
  static/images/rag-llm-gitops/launch-application.png
  static/images/rag-llm-gitops/monitoring.png
  static/images/rag-llm-gitops/proposal.png
  static/images/rag-llm-gitops/provider-1.png
  static/images/rag-llm-gitops/provider-2.png
  static/images/rag-llm-gitops/rag-llm.png
Labels: size/XL

#516 fix: incremental updates to the coco-pattern documentation
  content/patterns/coco-pattern/_index.adoc
  content/patterns/coco-pattern/coco-pattern-getting-started.adoc
Labels: size/XS, ok-to-test

#515 Agof v2 blog
  content/blog/2025-01-09-AGOF_v2.adoc
  static/images/agof/AGOFv2_Structure.png
Labels: size/L

#518 Add .gitleaks.toml file to ignore false warnings
  .gitleaks.toml
Labels: size/XS

#519 Metadata support work
  .github/workflows/metadata-docs.yml
  content/patterns/industrial-edge/cluster-sizing.adoc
  content/patterns/industrial-edge/cluster-sizing.md
  modules/cluster-sizing-template.adoc
  modules/industrial-edge/metadata-industrial-edge.adoc
  utils/flatten_yaml.rb
Labels: size/L

#520 Merge cluster variables change for industrial-edge
  modules/industrial-edge/metadata-industrial-edge.adoc
Labels: size/XS

#521 Use proper asciidoc comments when flattening metadata
  utils/flatten_yaml.rb
Labels: size/XS
