Repository validatedpatterns/docs, pull requests merged in 2025-07, with the labels that each got.

#576 Implement "Edit this page" along with "select text to report issue" feature
  .hintrc
  layouts/_default/baseof.html
  layouts/partials/select-report-issue-hover.html
  layouts/partials/select-report-issue-popup.html
  layouts/partials/toc.html
  static/js/select-report-issue-hover.js
  static/js/select-report-issue-popup.js
Labels: lgtm, size/L

#584 update partners for RAG LLM Gitops pattern
  content/patterns/rag-llm-gitops/_index.md
Labels: lgtm, size/XS

#588 Fix Asciidoctor build warnings
  content/learn/vp_add_ops_to_pattern.adoc
  content/patterns/amd-rag-chat-qna/amd-rag-chat-qna-getting-started.adoc
Labels: lgtm, needs-ok-to-test, size/S

#586 add blog post to introduce patternizer tool
  content/blog/2025-07-24-introducing-patternizer.adoc
Labels: lgtm, size/L
