Repository validatedpatterns/docs, pull requests merged in 2025-05, with the labels that each got.

#562 Adding variant functionality to patterns browser
  content/patterns/medical-diagnosis-amx/_index.adoc
  content/patterns/multicloud-gitops-Portworx/_index.md
  content/patterns/multicloud-gitops-amx-rhoai/_index.adoc
  content/patterns/multicloud-gitops-amx/_index.adoc
  content/patterns/multicloud-gitops-qat/_index.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/_index.adoc
  content/patterns/multicloud-gitops-sgx/_index.adoc
  layouts/partials/menu-patterns-browser.html
  layouts/partials/patterns-browser.html
  static/js/patterns-browser-v2.js
Labels: lgtm, size/L

#567 Add docs to accompany AMD-accelerated OPEA ChatQnA pattern
  content/patterns/amd-rag-chat-qna/_index.adoc
  content/patterns/amd-rag-chat-qna/amd-rag-chat-qna-getting-started.adoc
  content/patterns/amd-rag-chat-qna/amd-rag-chat-qna-required-hardware.adoc
  content/patterns/amd-rag-chat-qna/amd-rag-chat-qna-troubleshooting.adoc
  modules/comm-attributes.adoc
  static/images/qna-chat-amd/amd-rag-chat-qna-flow.png
  static/images/qna-chat-amd/amd-rag-chat-qna-overview.png
  static/images/qna-chat-amd/chatqna-delete-file.png
  static/images/qna-chat-amd/chatqna-long-response.png
  static/images/qna-chat-amd/chatqna-request-response.png
  static/images/qna-chat-amd/chatqna-ui-no-rag.png
  static/images/qna-chat-amd/chatqna-upload-file.jpeg
  static/images/qna-chat-amd/chatqna-upload-icon.jpeg
  static/images/qna-chat-amd/rhoai-create-connection-2.png
  static/images/qna-chat-amd/rhoai-create-connection.png
  static/images/qna-chat-amd/rhoai-create-workbench.png
  static/images/qna-chat-amd/rhoai-upload-model.png
Labels: lgtm, ok-to-test, size/XL

#571 TELCODOCS-2337: Add GitHub repo links in pattern headers
  content/patterns/amd-rag-chat-qna/_index.adoc
  content/patterns/ansible-edge-gitops-kasten/_index.md
  content/patterns/ansible-edge-gitops/_index.adoc
  content/patterns/ansible-gitops-framework/_index.md
  content/patterns/cockroachdb/_index.md
  content/patterns/coco-pattern/_index.adoc
  content/patterns/connected-vehicle-architecture/_index.md
  content/patterns/devsecops/_index.md
  content/patterns/emerging-disease-detection/_index.adoc
  content/patterns/federated-edge-observability/_index.adoc
  content/patterns/gaudi-rag-chat-qna/_index.adoc
  content/patterns/hypershift/_index.adoc
  content/patterns/industrial-edge/_index.md
  content/patterns/kong-gateway/_index.md
  content/patterns/medical-diagnosis-amx/_index.adoc
  content/patterns/medical-diagnosis/_index.adoc
  content/patterns/mlops-fraud-detection/_index.adoc
  content/patterns/multicloud-gitops-Portworx/_index.md
  content/patterns/multicloud-gitops-amx-rhoai/_index.adoc
  content/patterns/multicloud-gitops-amx/_index.adoc
  content/patterns/multicloud-gitops-qat/_index.adoc
  content/patterns/multicloud-gitops-sgx-hello-world/_index.adoc
  content/patterns/multicloud-gitops-sgx/_index.adoc
  content/patterns/multicloud-gitops/_index.adoc
  content/patterns/openshift-ai/_index.adoc
  content/patterns/rag-llm-gitops/_index.md
  content/patterns/regional-dr/_index.md
  content/patterns/retail/_index.adoc
  content/patterns/travelops/_index.adoc
  content/patterns/virtualization-starter-kit/_index.md
  layouts/partials/links.html
Labels: jira/valid-reference, size/M
