Repository validatedpatterns/docs, pull requests merged in 2025-09, with the labels that each got.

#596 Disable old preview workflows
  .github/workflows/gh-pages.yml
  .github/workflows/preview-message.yml
Labels: lgtm, size/M

#599 Update documentation issue template description under 200 chars
  .github/ISSUE_TEMPLATE/docs-feedback.yml
Labels: lgtm, size/XS

#598 Added Matomo analytics script
  layouts/partials/head.html
Labels: lgtm, size/S

#600 Restore gh-pages workflow
  .github/workflows/gh-pages.yml
Labels: lgtm, size/M

#603 add information about elasticsearch to rag-llm docs
  content/patterns/rag-llm-gitops/_index.md
  content/patterns/rag-llm-gitops/deploying-different-db.md
  content/patterns/rag-llm-gitops/getting-started.md
  static/images/rag-llm-gitops/rag-augmented-query.png
Labels: lgtm, size/L

#606 chore: Removed duplicate Managed cluster sites file
  content/patterns/multicloud-gitops/retail-managed-cluster.adoc
Labels: lgtm, size/M
