Repository validatedpatterns/docs, pull requests merged in 2025-04, with the labels that each got.

#559 ML CI/CD part 1
  content/patterns/industrial-edge/application.md
  static/images/industrial-edge/elyra-pipeline-submit.png
  static/images/industrial-edge/elyra-pipeline.png
  static/images/industrial-edge/pipeline-commit.png
  static/images/industrial-edge/rhoai-pipeline.png
Labels: size/M, ok-to-test

#560 Fix ie image display
  content/patterns/industrial-edge/application.md
Labels: size/XS

#558 TELCODOCS-2245 Updating hypershift vp docs
  content/patterns/hypershift/getting-started.adoc
  static/images/hypershift/hypershift-cluster-details.png
  static/images/hypershift/hypershift-cluster-list.png
  static/images/hypershift/hypershift-ops-applications.png
  static/images/hypershift/hypershift-ops.png
Labels: size/L

#561 updated industrial edge data diagram
  static/images/industrial-edge/edge-mfg-devops-data-sd.png
Labels: size/XS, ok-to-test

#563 Adding OpenShift Virt Card
  content/patterns/modern-virtualization/_index.md
  content/patterns/modern-virtualization/ansible-automation-platform.md
  content/patterns/modern-virtualization/cluster-sizing.md
  content/patterns/modern-virtualization/getting-started.md
  content/patterns/modern-virtualization/ideas-for-customization.md
  content/patterns/modern-virtualization/installation-details.md
  content/patterns/modern-virtualization/openshift-virtualization.md
  content/patterns/modern-virtualization/troubleshooting.md
Labels: size/XXL

#555 Telcodocs 2229 update retail VP
  content/learn/vp_add_ops_to_pattern.adoc
  content/learn/vp_add_specific_ops_to_pattern.adoc
  content/patterns/multicloud-gitops/retail-managed-cluster.adoc
  content/patterns/retail/_index.adoc
  content/patterns/retail/_index.md
  content/patterns/retail/application.adoc
  content/patterns/retail/application.md
  content/patterns/retail/cluster-sizing.adoc
  content/patterns/retail/cluster-sizing.md
  content/patterns/retail/components.adoc
  content/patterns/retail/components.md
  content/patterns/retail/getting-started.adoc
  content/patterns/retail/getting-started.md
  content/patterns/retail/ideas-for-customization.md
  content/patterns/retail/store.adoc
  content/patterns/retail/store.md
  content/patterns/retail/troubleshooting.md
  content/patterns/travelops/cluster-sizing.adoc
  modules/comm-deploying-managed-cluster-using-cm-cli-tool.adoc
  modules/retail-about.adoc
  modules/retail-architecture.adoc
  modules/retail-deploying.adoc
  modules/retail-example-applications.adoc
  modules/retail-understanding-rhacm-requirements.adoc
  static/images/retail/retail-v1-landing-page-1.png
  static/images/retail/retail-v1-landing-page.png
Labels: size/XXL

#564 Document virtualization starter kit
  content/patterns/modern-virtualization/_index.md
  content/patterns/modern-virtualization/ansible-automation-platform.md
  content/patterns/modern-virtualization/cluster-sizing.md
  content/patterns/modern-virtualization/getting-started.md
  content/patterns/modern-virtualization/ideas-for-customization.md
  content/patterns/modern-virtualization/troubleshooting.md
  content/patterns/virtualization-starter-kit/_index.md
  content/patterns/virtualization-starter-kit/getting-started.md
  content/patterns/virtualization-starter-kit/ideas-for-customization.md
  content/patterns/virtualization-starter-kit/installation-details.md
  content/patterns/virtualization-starter-kit/openshift-virtualization.md
  content/patterns/virtualization-starter-kit/troubleshooting.md
  static/images/virtualization-starter-kit/aeg-console-vm-template-1.png
  static/images/virtualization-starter-kit/aeg-open-vm-console.png
  static/images/virtualization-starter-kit/aeg-show-vms.png
  static/images/virtualization-starter-kit/console-vm-spinning-up.png
  static/images/virtualization-starter-kit/console-vm-template-wizard-success.png
  static/images/virtualization-starter-kit/console-vm-template-wizard.png
  static/images/virtualization-starter-kit/vsk-applications.png
  static/images/virtualization-starter-kit/vsk-new-operators.png
  static/images/virtualization-starter-kit/vsk-openshift-vm-screen.png
Labels: size/XXL

#566 Update _index.md
  content/_index.md
Labels: size/XS

#565 Add Virtualization Starter Kit blog entry
  content/blog/2025-04-24-VSK_blog.adoc
Labels: size/M
